/* ============================================================
   Studio chatbot knowledge base — pricing + client FAQ, 5 langs.
   Keyword-matched (substring, longest match wins): each entry has
   k (trigger words — keep them as robust SINGLE words) and a (HTML answer).
   Loaded after i18n.js, so it replaces the basic CHAT_I18N there.
   ============================================================ */
window.CHAT_I18N = {

  /* ---------------- ENGLISH ---------------- */
  "en": {
    "greet": "Hi! 👋 I'm Barakat's studio assistant. Ask me about <b>services</b>, <b>pricing</b>, <b>timeline</b>, or how to <b>start a project</b>.",
    "fallback": "I'm not sure about that — but Barakat can help directly. Try the <b>Contact</b> room, or ask me about <i>pricing, timeline, revisions, payment, files, or services</i>.",
    "quick": [{ "label": "Pricing", "q": "price" }, { "label": "Services", "q": "services" }, { "label": "Timeline", "q": "how long" }, { "label": "Contact", "q": "contact" }],
    "kb": [
      { "k": ["service", "what do you", "offer", "do you do"], "a": "Barakat offers <b>brand identity & logo design</b>, <b>editorial & book covers</b>, <b>posters</b>, <b>social media</b>, <b>print & invoices</b>, and <b>video & motion graphics</b>. Want a category? Open the Design room tabs." },
      { "k": ["price", "pricing", "cost", "how much", "budget", "rate", "fee", "quote"], "a": "Pricing depends on scope. Starting ranges:<br>• <b>Logo</b> — $100 → $1,500+<br>• <b>Full brand identity</b> — $250 → $2,500<br>• <b>Poster</b> — $15 → $150<br>• <b>Social post</b> — $10 → $25<br>• <b>Video (per min)</b> — from $100<br>• <b>Monthly management</b> — $250 → $1,000+<br>For an exact quote, send a brief via the <b>Contact</b> room." },
      { "k": ["logo", "branding", "identity", "brand"], "a": "<b>Logo & branding:</b><br>• Logo design — from <b>$100</b> (basic) up to <b>$1,500+</b> (full professional)<br>• Full brand identity (logo, business card, folder, poster) — <b>$250 → $2,500</b><br>It's a mark, not just a picture — and the copyright is fully yours. See the <b>Logo</b> tab for examples." },
      { "k": ["print", "poster", "business card", "card", "invoice", "letterhead", "book cover", "layout"], "a": "<b>Print & advertising:</b><br>• Poster — <b>$15 → $150</b><br>• Business card — <b>$10 → $25</b><br>• Invoice / letterhead — <b>$10 → $20</b> each<br>• Book cover — <b>$50 → $100</b><br>• Inside-page layout — <b>$1.5 → $2.5</b> per page" },
      { "k": ["social post", "single post", "post price", "carousel", "image edit", "retouch"], "a": "<b>Social media & images:</b><br>• Single post — <b>$10 → $25</b><br>• Carousel (multi-image) — <b>$25 → $60</b><br>• Image editing / retouching — <b>$10 → $20</b> per image" },
      { "k": ["video", "motion", "reel", "montage", "animation", "edit video"], "a": "<b>Video & motion:</b><br>• Commercial / cinematic video — from <b>$100 per minute</b> (more if filming is included, up to $1,500)<br>• Motion graphics — <b>$3 → $10 per second</b> ($200–$600 a minute)<br>• Reels / shorts (simple edit) — <b>$15 → $40</b>" },
      { "k": ["management", "manage", "monthly", "package", "retainer", "run my page"], "a": "<b>Social media management</b> (monthly):<br>• Basic (8–10 posts + simple edits + message replies) — <b>$250 → $400</b><br>• Mid (15 posts + boosting + video) — <b>$500 → $800</b><br>• Pro (full platform management + marketing plan) — <b>$1,000+</b>" },
      { "k": ["expensive", "why so", "too much", "cheaper", "why cost", "just an image", "overpriced"], "a": "A logo isn't just a picture — it's the <b>face</b> of your business. You're not paying for a drawing; you're paying for the research, experience, and strategy that make your brand stand out among hundreds of competitors. Cheap design often means losing customers and weakening your brand." },
      { "k": ["how long", "timeline", "time", "when ready", "deadline", "duration", "delivery", "ready"], "a": "Typical timing: <b>logo 3–7 working days</b>, a social post in <b>24–48 hours</b>, a full identity in <b>3–5 weeks</b>, a book cover in <b>~1 week</b>. I give you a fixed deadline and stick to it. Urgent work is possible (a small rush fee applies)." },
      { "k": ["revision", "don't like", "didn't like", "not happy", "changes", "edit it", "redo"], "a": "Before starting, we agree on a <b>moodboard</b> (colors & style) so I understand your taste. If it's still not right, I include <b>2–3 free revisions</b> until we reach the final result." },
      { "k": ["pay", "payment", "deposit", "advance", "upfront", "installment"], "a": "Payment is split: <b>50% deposit</b> before starting, and the remaining <b>50%</b> after final approval and before sending the source files." },
      { "k": ["refund", "money back", "cancel", "cancelled"], "a": "The deposit is non-refundable, because that amount is reserved for the time and effort already spent on research and starting your project." },
      { "k": ["discount", "lower", "reduce", "cheaper price", "negotiate", "tight budget"], "a": "Prices are set by the time and effort a project takes. If your budget is tight, we can reduce the <b>scope</b> (e.g. 3 posts instead of 5) to fit it — but I never reduce the quality of the work." },
      { "k": ["file", "format", "png", "psd", "jpg", "vector", "deliver"], "a": "You get every format you need: <b>PNG</b> (transparent), <b>JPG</b> (social media), and the editable source files (<b>AI / PSD</b>) for print and future use." },
      { "k": ["cmyk", "rgb", "print color", "print quality", "color differ", "dpi", "darker"], "a": "Print files are prepared in <b>CMYK</b> at <b>300 dpi</b> so colors come out accurately. Screens use RGB (light) and print uses CMYK (ink), so a tiny color difference between screen and print is always natural." },
      { "k": ["source file", "own the", "ownership", "open file", "editable", "give me the"], "a": "Logo & brand source files (vector) are <b>yours</b> — they belong to your business. For social posts and video, the editable working files (PSD/AEP) are part of my effort; if you want them for future edits, a set fee is added." },
      { "k": ["original", "copy", "copied", "template", "unique", "stolen", "copyright"], "a": "Every work starts from scratch with idea + sketch. I guarantee your logo is <b>unique and the copyright is yours</b> — never a ready-made Google image or template. If anyone copies it, I provide all the creation stages so you can prove it's yours." },
      { "k": ["rush", "urgent", "fast", "quick", "today", "hurry", "asap"], "a": "Yes, urgent work is possible — I can make room in my schedule, but a <b>rush fee</b> applies, since I have to pause other clients' work and put in extra hours." },
      { "k": ["who", "about", "experience", "barakat", "years"], "a": "Barakat Qurtas — independent graphic designer in <b>Hewlêr, Kurdistan</b> since <b>2014</b> (12+ years), now with the Media Affairs Directorate at the Presidency. 1000+ works in print & digital." },
      { "k": ["language", "speak"], "a": "Barakat works in <b>Kurdish (Sorani & Kurmancî)</b>, <b>Arabic</b>, <b>English</b>, and some <b>French</b>." },
      { "k": ["contact", "email", "phone", "whatsapp", "hire", "reach", "start"], "a": "Easiest ways to reach Barakat:<br>• ✉️ <a href='mailto:info@bqurtas.com'>info@bqurtas.com</a><br>• 📱 <a href='https://wa.me/9647517884985' target='_blank' rel='noopener'>WhatsApp +964 751 788 4985</a><br>Or open the <b>Contact</b> room and send a short brief." },
      { "k": ["book", "cover"], "a": "Book covers are a specialty — 99+ covers. Open the <b>Book</b> tab in the Design room. A cover starts from <b>$50</b>, inside layout from <b>$1.5</b> per page." },
      { "k": ["hi", "hello", "hey"], "a": "Hi! 👋 I'm Barakat's studio assistant. Ask me about services, pricing, timeline, or starting a project." },
      { "k": ["thanks", "thank", "thx"], "a": "You're welcome! Anything else you'd like to know? 🙂" }
    ]
  },

  /* ---------------- KURDISH (Sorani) ---------------- */
  "ku": {
    "greet": "سڵاو! 👋 من یاریدەدەری ستۆدیۆی بەرەکاتم. پرسیارم لێبکە دەربارەی <b>خزمەتگوزاری</b>، <b>نرخ</b>، <b>کات</b>، یان دەستپێکردنی <b>پڕۆژە</b>.",
    "fallback": "دڵنیا نیم لەوە — بەڵام بەرەکات ڕاستەوخۆ یارمەتیت دەدات. ژووری <b>پەیوەندی</b> تاقیبکەرەوە، یان پرسیارم لێبکە دەربارەی <i>نرخ، کات، دەستکاری، پارەدان، فایل، یان خزمەتگوزاری</i>.",
    "quick": [{ "label": "نرخ", "q": "نرخ" }, { "label": "خزمەتگوزاری", "q": "خزمەت" }, { "label": "کات", "q": "کات" }, { "label": "پەیوەندی", "q": "پەیوەندی" }],
    "kb": [
      { "k": ["خزمەت", "چی دەکەی", "پێشکەش", "چ کارێک"], "a": "بەرەکات پێشکەشی <b>ناسنامەی بران و لۆگۆ</b>، <b>ئەدیتۆریاڵ و بەرگی کتێب</b>، <b>پۆستەر</b>، <b>سۆشیال میدیا</b>، <b>چاپ و پسووڵە</b>، و <b>ڤیدیۆ و مۆشن گرافیک</b> دەکات. دەتەوێت بەشێک ببینیت؟ تابەکانی ژووری دیزاین بکەرەوە." },
      { "k": ["نرخ", "چەند", "بودجە", "تێچوو", "بەها", "پارە چەند"], "a": "نرخ بەپێی قەبارە دەگۆڕێت. خاڵی دەستپێک:<br>• <b>لۆگۆ</b> — ١٠٠$ → ١٥٠٠$+<br>• <b>ناسنامەی تەواو</b> — ٢٥٠$ → ٢٥٠٠$<br>• <b>پۆستەر</b> — ١٥$ → ١٥٠$<br>• <b>پۆستی سۆشیاڵ</b> — ١٠$ → ٢٥$<br>• <b>ڤیدیۆ (هەر دەقیقە)</b> — لە ١٠٠$<br>• <b>بەڕێوەبردنی مانگانە</b> — ٢٥٠$ → ١٠٠٠$+<br>بۆ نرخی ورد، کورتەیەک بنێرە لە ژووری <b>پەیوەندی</b>." },
      { "k": ["لۆگۆ", "براند", "ناسنامە", "براندینگ", "مۆر"], "a": "<b>لۆگۆ و ناسنامەی بران:</b><br>• دیزاینی لۆگۆ — لە <b>١٠٠$</b> (سادە) تا <b>١٥٠٠$+</b> (پرۆفیشناڵی تەواو)<br>• ناسنامەی تەواو (لۆگۆ، بزنس کارد، فۆڵدەر، پۆستەر) — <b>٢٥٠$ → ٢٥٠٠$</b><br>لۆگۆ نیشانەیە نەک تەنها وێنە — و مافی یاسایی تەواو هی تۆیە. نموونە لە تابی <b>لۆگۆ</b> ببینە." },
      { "k": ["پۆستەر", "چاپ", "بزنس کارد", "کارت", "پسووڵە", "وەسڵ", "بەرگی کتێب", "ڕیکلام"], "a": "<b>چاپەمەنی و ڕیکلام:</b><br>• پۆستەر — <b>١٥$ → ١٥٠$</b><br>• بزنس کارد — <b>١٠$ → ٢٥$</b><br>• وەسڵ / پسووڵە — <b>١٠$ → ٢٠$</b> بۆ هەر دانە<br>• بەرگی کتێب — <b>٥٠$ → ١٠٠$</b><br>• ڕێکخستنی لاپەڕەی ناوەوە — <b>١.٥$ → ٢.٥$</b> بۆ هەر لاپەڕە" },
      { "k": ["پۆست", "کارۆسێل", "دەستکاری وێنە", "ریتاچ", "تک پۆست"], "a": "<b>سۆشیاڵ میدیا و وێنە:</b><br>• تک پۆست — <b>١٠$ → ٢٥$</b><br>• کارۆسێل (چەند وێنەیی) — <b>٢٥$ → ٦٠$</b><br>• دەستکاری/ڕیتاچی وێنە — <b>١٠$ → ٢٠$</b> بۆ هەر وێنە" },
      { "k": ["ڤیدیۆ", "مۆشن", "ڕیڵز", "مۆنتاژ", "ئەنیمەیشن"], "a": "<b>ڤیدیۆ و مۆشن:</b><br>• ڤیدیۆی ڕیکلامی / سینەماتیک — لە <b>١٠٠$ بۆ هەر دەقیقە</b> (لەگەڵ وێنەگرتن تا ١٥٠٠$)<br>• مۆشن گرافیک — <b>٣$ → ١٠$ بۆ هەر چرکە</b> (٢٠٠$–٦٠٠$ بۆ دەقیقەیەک)<br>• ڕیڵز / شۆرتس (مۆنتاژی سادە) — <b>١٥$ → ٤٠$</b>" },
      { "k": ["بەڕێوەبردن", "مانگانە", "پاکێج", "پەیج", "بەڕێوە ببە"], "a": "<b>بەڕێوەبردنی سۆشیاڵ میدیا</b> (مانگانە):<br>• سادە (٨–١٠ پۆست + مۆنتاژی سادە + وەڵامی نامە) — <b>٢٥٠$ → ٤٠٠$</b><br>• مامناوەند (١٥ پۆست + سپۆنسەر + ڤیدیۆ) — <b>٥٠٠$ → ٨٠٠$</b><br>• پرۆفیشناڵ (بەڕێوەبردنی تەواو + پلانی مارکێتینگ) — <b>١٠٠٠$+</b>" },
      { "k": ["گران", "بۆچی ئەوەندە", "هەرزان", "تەنها وێنە", "بۆ گرانە"], "a": "لۆگۆ تەنها وێنە نییە — <b>دەموچاوی</b> بزنسەکەتە. تۆ پارە بۆ کێشانی وێنەکە نادەیت، بەڵکو بۆ ئەو لێکۆڵینەوە و ئەزموون و ستراتیژییەی کە وادەکات براندەکەت لەناو سەدان ڕکابەردا بناسرێتەوە. هەرزانی لە دیزایندا زۆرجار بە واتای لەدەستدانی کڕیار و لاوازبوونی براندەکەت دێت." },
      { "k": ["کات", "ماوە", "چەند دەخایەنێت", "کەی تەواو", "خایاندن"], "a": "کاتە ئاساییەکان: <b>لۆگۆ ٣–٧ ڕۆژی کارکردن</b>، پۆستی سۆشیاڵ لە <b>٢٤–٤٨ کاتژمێر</b>، ناسنامەی تەواو لە <b>٣–٥ هەفتە</b>، بەرگی کتێب لە <b>~١ هەفتە</b>. کاتێکی دیاریکراوت دەدەمێ و پابەند دەبم پێوەی. کاری خێراش دەکرێت (نرخی فریاکەوتنی کەمی دەچێتە سەر)." },
      { "k": ["دەستکاری", "بەدڵ نەبوو", "بەدڵم نییە", "گۆڕین", "ریڤیژن", "ناڕازی"], "a": "پێش دەستپێکردن، <b>موودبۆرد</b> (ڕەنگ و ستایل) دیاری دەکەین تاکو سەلیقەکەت بزانم. ئەگەر دوای ئەوەش بەدڵت نەبوو، <b>٢–٣ جار دەستکاری بەخۆڕایی</b> دەکەم تا دەگەینە ئەنجامی کۆتایی." },
      { "k": ["پارە", "پارەدان", "پێشەکی", "دیپۆزیت", "چۆن بدەم"], "a": "شێوازی پارەدان: <b>٥٠٪ پێشەکی</b> پێش دەستپێکردن، و <b>٥٠٪</b>ـی تر دوای پەسەندکردنی کۆتایی و پێش ناردنی فایلە ڕەسەنەکان." },
      { "k": ["گەڕانەوەی پارە", "هەڵوەشایەوە", "وازهێنان", "پارەم دەگەڕێتەوە"], "a": "پێشەکییەکە ناگەڕێتەوە، چونکە ئەو بڕە پارەیە تەرخان کراوە بۆ ئەو کات و ماندووبوونەی کە بۆ لێکۆڵینەوە و دەستپێکی پڕۆژەکە خەرج کراوە." },
      { "k": ["داشکاندن", "کەمکردنەوە", "ئەرزانتر", "بودجەم کەمە", "تخفیض"], "a": "نرخەکان بەپێی کات و ماندووبوونی پڕۆژەکە دانراون. ئەگەر بودجەکەت سنووردارە، دەتوانین <b>بڕی کارەکان</b> کەم بکەینەوە (وەک ٣ پۆست لەبری ٥) تاکو بگونجێت — بەڵام کوالێتی کارەکە کەم ناکەمەوە." },
      { "k": ["فایل", "فۆرمات", "png", "psd", "jpg", "ڤێکتەر"], "a": "هەموو فۆرماتە پێویستەکانت دەدەمێ: <b>PNG</b> (بێ باکگراوند)، <b>JPG</b> (بۆ سۆشیاڵ میدیا)، و فایلە ڕەسەنەکان (<b>AI / PSD</b>) بۆ چاپ و داهاتوو." },
      { "k": ["cmyk", "rgb", "ڕەنگی چاپ", "کوالێتی چاپ", "ڕەنگ جیاواز", "تاریکتر"], "a": "فایلی چاپ بە سیستەمی <b>CMYK</b> و کوالێتی <b>٣٠٠dpi</b> ئامادە دەکەم بۆ ئەوەی ڕەنگەکان بە وردی دەربچن. شاشە بە ڕووناکی (RGB) کار دەکات و چاپ بە مەرەکەب (CMYK)، بۆیە جیاوازییەکی زۆر کەم لە نێوان شاشە و چاپدا هەمیشە سروشتییە." },
      { "k": ["فایلی ڕەسەن", "سۆرس", "خاوەندارێتی", "فایلی کراوە", "فایلەکەم بدە"], "a": "فایلە ڕەسەنەکانی لۆگۆ و ناسنامە (ڤێکتەر) <b>هی تۆن</b> — موڵکی بزنسەکەتن. بەڵام بۆ پۆستی سۆشیاڵ و ڤیدیۆ، فایلە کراوەکان (PSD/AEP) بەشێکن لە ماندووبوونم؛ ئەگەر دەتەوێت بۆ گۆڕانکاری داهاتوو، بڕێک پارەی دیاریکراوی بۆ زیاد دەکرێت." },
      { "k": ["ڕەسەن", "کۆپی", "تەمپلەیت", "تایبەت", "کۆپیڕایت", "مافی یاسایی"], "a": "هەموو کارێک لە سفرەوە بە بیرۆکە و سکێچ دەست پێ دەکات. گەرەنتیت دەدەم لۆگۆکەت <b>تایبەت بێت و مافی یاسایی (Copyright) بۆ تۆ بێت</b> — نەک وێنەیەکی ئامادەی گووگڵ یان قاڵب. ئەگەر کەسێک کۆپی بکات، هەموو قۆناغەکانی دروستکردنت دەدەمێ بۆ سەلماندنی." },
      { "k": ["خێرا", "فریاکەوتن", "زوو", "بەپەلە", "ئەمڕۆ"], "a": "بەڵێ، کاری خێرا دەکرێت — دەتوانم جێگەی بۆ بکەمەوە، بەڵام <b>نرخی فریاکەوتن (Rush Fee)</b> دەچێتە سەر، چونکە دەبێ کارەکانی تری کڕیارەکان ڕابگرم و کاتژمێری زیادە کار بکەم." },
      { "k": ["کێیە", "دەربارە", "ئەزموون", "بەرەکات", "چەند ساڵ"], "a": "بەرەکات قورتاس — دیزاینەری گرافیکی سەربەخۆ لە <b>هەولێر، کوردستان</b> لە <b>٢٠١٤</b>ـەوە (١٢+ ساڵ)، ئێستا لەگەڵ بەڕێوەبەرایەتیی کاروباری ڕاگەیاندن لە نووسینگەی سەرۆک. ١٠٠٠+ کار لە چاپ و دیجیتاڵ." },
      { "k": ["زمان", "قسە دەکات"], "a": "بەرەکات بە <b>کوردی (سۆرانی و کرمانجی)</b>، <b>عەرەبی</b>، <b>ئینگلیزی</b>، و هەندێک <b>فەرەنسی</b> کار دەکات." },
      { "k": ["پەیوەندی", "ئیمەیل", "تەلەفۆن", "واتساب", "دامەزراندن", "دەستپێک"], "a": "ئاسانترین ڕێگا بۆ پەیوەندی بە بەرەکات:<br>• ✉️ <a href='mailto:info@bqurtas.com'>info@bqurtas.com</a><br>• 📱 <a href='https://wa.me/9647517884985' target='_blank' rel='noopener'>WhatsApp +964 751 788 4985</a><br>یان ژووری <b>پەیوەندی</b> بکەرەوە و کورتەیەک بنێرە." },
      { "k": ["کتێب", "بەرگ"], "a": "بەرگی کتێب تایبەتمەندییەکی منە — ٩٩+ بەرگ. تابی <b>کتێب</b> لە ژووری دیزاین بکەرەوە. بەرگ لە <b>٥٠$</b> دەست پێ دەکات، ڕێکخستنی ناوەوە لە <b>١.٥$</b> بۆ هەر لاپەڕە." },
      { "k": ["سڵاو", "های", "سلاو"], "a": "سڵاو! 👋 من یاریدەدەری ستۆدیۆی بەرەکاتم. پرسیارم لێبکە دەربارەی خزمەتگوزاری، نرخ، کات، یان دەستپێکردنی پڕۆژە." },
      { "k": ["سوپاس", "زۆر سوپاس"], "a": "شایانی نییە! شتی تر هەیە بزانیت؟ 🙂" }
    ]
  },

  /* ---------------- ARABIC ---------------- */
  "ar": {
    "greet": "مرحبًا! 👋 أنا مساعد استوديو بركات. اسألني عن <b>الخدمات</b> أو <b>الأسعار</b> أو <b>الوقت</b> أو كيفية بدء <b>مشروع</b>.",
    "fallback": "لست متأكدًا من ذلك — لكن بركات يساعدك مباشرة. جرّب غرفة <b>التواصل</b>، أو اسألني عن <i>الأسعار، الوقت، التعديلات، الدفع، الملفات، أو الخدمات</i>.",
    "quick": [{ "label": "الأسعار", "q": "سعر" }, { "label": "الخدمات", "q": "خدمات" }, { "label": "الوقت", "q": "وقت" }, { "label": "تواصل", "q": "تواصل" }],
    "kb": [
      { "k": ["خدمات", "خدمة", "ماذا تفعل", "تقدم"], "a": "يقدّم بركات <b>الهوية البصرية وتصميم الشعارات</b>، <b>التصميم التحريري وأغلفة الكتب</b>، <b>الملصقات</b>، <b>وسائل التواصل</b>، <b>الطباعة والفواتير</b>، و<b>الفيديو والموشن جرافيك</b>. تريد رؤية فئة؟ افتح تبويبات غرفة التصميم." },
      { "k": ["سعر", "اسعار", "كم", "ميزانية", "تكلفة", "بكم"], "a": "السعر يعتمد على الحجم. نقاط البداية:<br>• <b>شعار</b> — 100$ ← 1500$+<br>• <b>هوية كاملة</b> — 250$ ← 2500$<br>• <b>ملصق</b> — 15$ ← 150$<br>• <b>منشور سوشيال</b> — 10$ ← 25$<br>• <b>فيديو (للدقيقة)</b> — من 100$<br>• <b>إدارة شهرية</b> — 250$ ← 1000$+<br>لعرض دقيق، أرسل موجزًا عبر غرفة <b>التواصل</b>." },
      { "k": ["شعار", "لوغو", "هوية", "براندينغ", "علامة"], "a": "<b>الشعار والهوية البصرية:</b><br>• تصميم شعار — من <b>100$</b> (بسيط) حتى <b>1500$+</b> (احترافي كامل)<br>• هوية كاملة (شعار، كرت عمل، فولدر، ملصق) — <b>250$ ← 2500$</b><br>الشعار علامة وليس مجرد صورة — وحقوقه كاملة لك. شاهد تبويب <b>الشعارات</b>." },
      { "k": ["ملصق", "طباعة", "كرت", "كارت", "فاتورة", "غلاف", "بوستر"], "a": "<b>الطباعة والإعلان:</b><br>• ملصق — <b>15$ ← 150$</b><br>• كرت عمل — <b>10$ ← 25$</b><br>• فاتورة / ترويسة — <b>10$ ← 20$</b> للقطعة<br>• غلاف كتاب — <b>50$ ← 100$</b><br>• تنسيق الصفحات الداخلية — <b>1.5$ ← 2.5$</b> للصفحة" },
      { "k": ["منشور", "بوست", "كاروسيل", "تعديل صور", "ريتاتش"], "a": "<b>وسائل التواصل والصور:</b><br>• منشور واحد — <b>10$ ← 25$</b><br>• كاروسيل (عدة صور) — <b>25$ ← 60$</b><br>• تعديل/ريتاتش صورة — <b>10$ ← 20$</b> للصورة" },
      { "k": ["فيديو", "موشن", "ريلز", "مونتاج", "انميشن"], "a": "<b>الفيديو والموشن:</b><br>• فيديو إعلاني / سينمائي — من <b>100$ للدقيقة</b> (مع التصوير حتى 1500$)<br>• موشن جرافيك — <b>3$ ← 10$ للثانية</b> (200$–600$ للدقيقة)<br>• ريلز / شورتس (مونتاج بسيط) — <b>15$ ← 40$</b>" },
      { "k": ["ادارة", "إدارة", "شهري", "باقة", "صفحتي", "ادر"], "a": "<b>إدارة وسائل التواصل</b> (شهريًا):<br>• بسيطة (8–10 منشورات + مونتاج بسيط + رد رسائل) — <b>250$ ← 400$</b><br>• متوسطة (15 منشورًا + تمويل + فيديو) — <b>500$ ← 800$</b><br>• احترافية (إدارة كاملة + خطة تسويق) — <b>1000$+</b>" },
      { "k": ["غالي", "لماذا", "ارخص", "أرخص", "مجرد صورة", "مكلف"], "a": "الشعار ليس مجرد صورة — إنه <b>وجه</b> عملك. أنت لا تدفع مقابل رسم الصورة، بل مقابل البحث والخبرة والاستراتيجية التي تجعل علامتك تتميّز بين مئات المنافسين. الرخص في التصميم غالبًا يعني خسارة العملاء وإضعاف العلامة." },
      { "k": ["وقت", "مدة", "كم يستغرق", "متى", "تسليم", "جاهز"], "a": "المدد المعتادة: <b>شعار 3–7 أيام عمل</b>، منشور في <b>24–48 ساعة</b>، هوية كاملة في <b>3–5 أسابيع</b>، غلاف كتاب في <b>~أسبوع</b>. أعطيك موعدًا محددًا وألتزم به. العمل العاجل ممكن (مع رسم استعجال بسيط)." },
      { "k": ["تعديل", "لم يعجبني", "ما عجبني", "تغيير", "غير راضٍ", "تعديلات"], "a": "قبل البدء نتفق على <b>موودبورد</b> (الألوان والستايل) لأعرف ذوقك. وإن لم يعجبك بعدها، أقدّم <b>2–3 تعديلات مجانية</b> حتى نصل للنتيجة النهائية." },
      { "k": ["دفع", "ادفع", "أدفع", "مقدم", "عربون", "كيف ادفع"], "a": "طريقة الدفع: <b>50% مقدمًا</b> قبل البدء، و<b>50%</b> الباقية بعد الموافقة النهائية وقبل إرسال الملفات الأصلية." },
      { "k": ["استرداد", "الغاء", "إلغاء", "ترجيع", "فلوسي"], "a": "المقدّم غير قابل للاسترداد، لأنه مخصّص للوقت والجهد المبذول في البحث وبدء مشروعك." },
      { "k": ["خصم", "تخفيض", "ميزانيتي", "ارخص سعر"], "a": "الأسعار محدّدة حسب الوقت والجهد. إن كانت ميزانيتك محدودة، يمكننا تقليل <b>حجم العمل</b> (مثلًا 3 منشورات بدل 5) ليناسبها — لكنني لا أقلّل جودة العمل." },
      { "k": ["ملف", "ملفات", "صيغة", "png", "psd", "فيكتور"], "a": "تحصل على كل الصيغ التي تحتاجها: <b>PNG</b> (بدون خلفية)، <b>JPG</b> (للسوشيال)، والملفات الأصلية القابلة للتعديل (<b>AI / PSD</b>) للطباعة والمستقبل." },
      { "k": ["cmyk", "rgb", "لون الطباعة", "جودة طباعة", "اختلاف لون", "اغمق"], "a": "أجهّز ملفات الطباعة بنظام <b>CMYK</b> وجودة <b>300dpi</b> لتظهر الألوان بدقة. الشاشة تعمل بالضوء (RGB) والطباعة بالحبر (CMYK)، لذا فرق لوني بسيط بين الشاشة والطباعة أمر طبيعي دائمًا." },
      { "k": ["ملف اصلي", "سورس", "ملكية", "ملف مفتوح", "اعطني الملف"], "a": "ملفات الشعار والهوية الأصلية (فيكتور) <b>ملكك</b> لأنها ملك عملك. أما منشورات السوشيال والفيديو، فالملفات المفتوحة (PSD/AEP) جزء من جهدي؛ إن أردتها للتعديل مستقبلًا، يُضاف مبلغ محدّد." },
      { "k": ["اصلي", "أصلي", "نسخ", "قالب", "حصري", "حقوق"], "a": "كل عمل يبدأ من الصفر بفكرة ورسم. أضمن أن شعارك <b>حصري وحقوقه لك</b> — وليس صورة جاهزة من جوجل أو قالبًا. وإن نسخه أحد، أعطيك كل مراحل التصميم لتثبت أنه ملكك." },
      { "k": ["عاجل", "سريع", "بسرعة", "اليوم", "مستعجل"], "a": "نعم، العمل العاجل ممكن — أستطيع توفير مكان في جدولي، لكن يُضاف <b>رسم استعجال (Rush Fee)</b> لأنني أوقف أعمال عملاء آخرين وأعمل ساعات إضافية." },
      { "k": ["من", "عن", "خبرة", "بركات", "سنوات"], "a": "بركات قرطاس — مصمم جرافيك مستقل في <b>أربيل، كردستان</b> منذ <b>2014</b> (12+ سنة)، حاليًا مع مديرية الشؤون الإعلامية في مكتب الرئيس. أكثر من 1000 عمل في الطباعة والرقمي." },
      { "k": ["لغة", "لغات", "يتحدث"], "a": "يعمل بركات بـ<b>الكردية (سوراني وكرمانجي)</b>، <b>العربية</b>، <b>الإنجليزية</b>، وبعض <b>الفرنسية</b>." },
      { "k": ["تواصل", "بريد", "هاتف", "واتساب", "توظيف", "بدء"], "a": "أسهل طرق الوصول إلى بركات:<br>• ✉️ <a href='mailto:info@bqurtas.com'>info@bqurtas.com</a><br>• 📱 <a href='https://wa.me/9647517884985' target='_blank' rel='noopener'>WhatsApp +964 751 788 4985</a><br>أو افتح غرفة <b>التواصل</b> وأرسل موجزًا." },
      { "k": ["كتاب", "غلاف"], "a": "أغلفة الكتب تخصص — 99+ غلافًا. افتح تبويب <b>الكتب</b> في غرفة التصميم. الغلاف من <b>50$</b>، وتنسيق الداخل من <b>1.5$</b> للصفحة." },
      { "k": ["مرحبا", "اهلا", "أهلا", "سلام"], "a": "مرحبًا! 👋 أنا مساعد استوديو بركات. اسألني عن الخدمات أو الأسعار أو الوقت أو بدء مشروع." },
      { "k": ["شكرا", "شكرًا", "مشكور"], "a": "على الرحب والسعة! هل من شيء آخر تريد معرفته؟ 🙂" }
    ]
  },

  /* ---------------- KURMANCÎ ---------------- */
  "kmr": {
    "greet": "Slav! 👋 Ez alîkarê studyoya Barakat im. Ji min bipirse li ser <b>karûbar</b>, <b>biha</b>, <b>dem</b>, an destpêkirina <b>projeyek</b>.",
    "fallback": "Ne piştrast im — lê Barakat rasterast alîkar dike. Odeya <b>Têkilî</b> biceribîne, an ji min bipirse <i>biha, dem, guhertin, payment, dosye, an karûbar</i>.",
    "quick": [{ "label": "Biha", "q": "biha" }, { "label": "Karûbar", "q": "karûbar" }, { "label": "Dem", "q": "dem" }, { "label": "Têkilî", "q": "têkilî" }],
    "kb": [
      { "k": ["karûbar", "çi dikî", "pêşkêş", "kar"], "a": "Barakat <b>nasnameya brandê & logo</b>, <b>edîtoriyal & bergên pirtûkan</b>, <b>poster</b>, <b>medya civakî</b>, <b>çap & fatûre</b>, û <b>vîdyo & motion graphics</b> pêşkêş dike. Dixwazî kategoriyekê bibînî? Tabên odeya Design veke." },
      { "k": ["biha", "çiqas", "bûdce", "mesref", "bi çend"], "a": "Biha li gorî mezinahiyê ye. Xalên destpêkê:<br>• <b>Logo</b> — 100$ → 1500$+<br>• <b>Nasnameya temam</b> — 250$ → 2500$<br>• <b>Poster</b> — 15$ → 150$<br>• <b>Posta civakî</b> — 10$ → 25$<br>• <b>Vîdyo (her deqîqe)</b> — ji 100$<br>• <b>Birêvebirina mehane</b> — 250$ → 1000$+<br>Ji bo bihayeke rast, kurteyek bişîne odeya <b>Têkilî</b>." },
      { "k": ["logo", "brand", "nasname", "nîşan"], "a": "<b>Logo û nasnameya brandê:</b><br>• Sêwirana logo — ji <b>100$</b> (sade) heta <b>1500$+</b> (profesyonel)<br>• Nasnameya temam (logo, karta kar, folder, poster) — <b>250$ → 2500$</b><br>Logo nîşan e ne tenê wêne — û mafê wê yê te ye. Mînak li taba <b>Logo</b> bibîne." },
      { "k": ["poster", "çap", "karta kar", "kart", "fatûre", "berg"], "a": "<b>Çap & reklam:</b><br>• Poster — <b>15$ → 150$</b><br>• Karta kar — <b>10$ → 25$</b><br>• Fatûre / serkaxez — <b>10$ → 20$</b> ji bo her yek<br>• Bergê pirtûkê — <b>50$ → 100$</b><br>• Rêzkirina rûpelên hundir — <b>1.5$ → 2.5$</b> ji bo her rûpel" },
      { "k": ["post", "carousel", "sererastkirin", "wêne", "retûş"], "a": "<b>Medya civakî & wêne:</b><br>• Yek post — <b>10$ → 25$</b><br>• Carousel (gelek wêne) — <b>25$ → 60$</b><br>• Sererastkirin/retûşa wêneyê — <b>10$ → 20$</b> ji bo her wêne" },
      { "k": ["vîdyo", "motion", "reels", "montaj", "anîmasyon"], "a": "<b>Vîdyo & motion:</b><br>• Vîdyoya reklamî / sînematîk — ji <b>100$ ji bo deqîqeyek</b> (bi kişandinê heta 1500$)<br>• Motion graphics — <b>3$ → 10$ ji bo çirkeyek</b> (200$–600$ deqîqeyek)<br>• Reels / shorts (montaja sade) — <b>15$ → 40$</b>" },
      { "k": ["birêvebirin", "mehane", "pakêt", "rûpel", "bi rêve"], "a": "<b>Birêvebirina medya civakî</b> (mehane):<br>• Sade (8–10 post + montaja sade + bersiva nameyan) — <b>250$ → 400$</b><br>• Navîn (15 post + sponsor + vîdyo) — <b>500$ → 800$</b><br>• Profesyonel (birêvebirina temam + plana marketingê) — <b>1000$+</b>" },
      { "k": ["biha ye", "çima", "erzan", "tenê wêne", "biha çima"], "a": "Logo ne tenê wêne ye — <b>rûyê</b> karê te ye. Tu ne ji bo kişandina wêneyê didî, lê ji bo lêkolîn, ezmûn û stratejiya ku brandê te di nav sed hevrikan de cuda dike. Erzanî di sêwiranê de gelek caran tê maneya windakirina mişteriyan." },
      { "k": ["dem", "çiqas dem", "kengî", "amade", "dema"], "a": "Demên asayî: <b>logo 3–7 rojên kar</b>, postek di <b>24–48 saetan</b>, nasnameyeke temam di <b>3–5 hefte</b>, bergê pirtûkê di <b>~1 hefte</b> de. Ez demeke diyarkirî didim û pê ve girêdayî dimînim. Karê bilez mimkun e (bi rush fee-yeke biçûk)." },
      { "k": ["guhertin", "ne hat dilê", "ne eciband", "revision", "ne razî"], "a": "Berî destpêkê em li ser <b>moodboard</b> (reng û stayl) li hev dikin da ez zewqa te bizanim. Heke piştî wê jî ne hat dilê te, ez <b>2–3 guhertinên belaş</b> dikim heta em digihîjin encama dawî." },
      { "k": ["payment", "pere bidim", "pêşekî", "çawa bidim", "depozît"], "a": "Awayê payment: <b>50% pêşekî</b> berî destpêkê, û <b>50%</b> ya mayî piştî pejirandina dawî û berî şandina dosyeyên resen." },
      { "k": ["vegerandin", "betal", "vekişîn", "pereyê min"], "a": "Pêşekî venagere, ji ber ku ew pere ji bo dem û keda ku ji bo lêkolîn û destpêka projeyê hatî xerckirin veqetandî ye." },
      { "k": ["daxistin", "kêmkirin", "erzantir", "bûdceya min"], "a": "Biha li gorî dem û keda projeyê hatine danîn. Heke bûdceya te kêm e, em dikarin <b>mezinahiya karî</b> kêm bikin (mînak 3 post li şûna 5) — lê ez kalîteya karî kêm nakim." },
      { "k": ["dosye", "format", "png", "psd", "vektor"], "a": "Tu hemû formatên pêwîst distînî: <b>PNG</b> (bê background), <b>JPG</b> (ji bo civakî), û dosyeyên resen ên guherbar (<b>AI / PSD</b>) ji bo çap û pêşerojê." },
      { "k": ["cmyk", "rgb", "rengê çapê", "kalîteya çapê", "cudahiya reng", "tarîtir"], "a": "Dosyeyên çapê bi sîstema <b>CMYK</b> û kalîteya <b>300dpi</b> amade dikim da reng rast derkevin. Ekran bi ronahî (RGB) û çap bi hibrê (CMYK) dixebite, lewma cudahiyeke rengî ya biçûk di navbera ekran û çapê de her tim siruştî ye." },
      { "k": ["dosyeya resen", "source", "xwedîtî", "dosyeya vekirî", "dosyeya min bide"], "a": "Dosyeyên resen ên logo û nasnameyê (vektor) <b>yên te ne</b> — milkê karê te ne. Lê ji bo postên civakî û vîdyo, dosyeyên vekirî (PSD/AEP) beşek ji keda min in; heke ji bo guhertinê dixwazî, mebleğeke diyarkirî tê zêdekirin." },
      { "k": ["resen", "copy", "şablon", "taybet", "maf"], "a": "Her kar ji sifirê bi raman û sketch dest pê dike. Ez garantî didim logoya te <b>taybet e û mafê wê yê te ye</b> — ne wêneyeke amade ya Google an şablon. Heke yek copy bike, hemû qonaxên çêkirinê didim te ji bo îsbatê." },
      { "k": ["bilez", "lezgîn", "zû", "îro", "lez"], "a": "Erê, karê bilez mimkun e — ez dikarim cî di bernameya xwe de çêkim, lê <b>rush fee</b> tê zêdekirin, ji ber ku ez karên mişteriyên din rawestînim û saetên zêde dixebitim." },
      { "k": ["kî", "derbarê", "ezmûn", "barakat", "sal"], "a": "Barakat Qurtas — sêwirmendê grafîk ê serbixwe li <b>Hewlêr, Kurdistan</b> ji <b>2014</b> (12+ sal), niha bi Bereyê Karûbarên Medyayê li Nivîsgeha Serok. 1000+ kar di çap û dîjîtal de." },
      { "k": ["ziman", "diaxive"], "a": "Barakat bi <b>Kurdî (Soranî & Kurmancî)</b>, <b>Erebî</b>, <b>Îngilîzî</b>, û hinekî <b>Fransî</b> dixebite." },
      { "k": ["têkilî", "e-name", "telefon", "whatsapp", "kar bidim", "destpêk"], "a": "Rêya herî hêsan ji bo gihîştina Barakat:<br>• ✉️ <a href='mailto:info@bqurtas.com'>info@bqurtas.com</a><br>• 📱 <a href='https://wa.me/9647517884985' target='_blank' rel='noopener'>WhatsApp +964 751 788 4985</a><br>An odeya <b>Têkilî</b> veke û kurteyek bişîne." },
      { "k": ["pirtûk", "bergê"], "a": "Bergên pirtûkan pisporî ne — 99+ berg. Taba <b>Pirtûk</b> li odeya Design veke. Berg ji <b>50$</b>, rêzkirina hundir ji <b>1.5$</b> ji bo her rûpel." },
      { "k": ["slav", "silav", "merheba"], "a": "Slav! 👋 Ez alîkarê studyoya Barakat im. Ji min bipirse karûbar, biha, dem, an destpêkirina projeyê." },
      { "k": ["spas", "gelek spas"], "a": "Bi xêr hatî! Tiştek din heye ku tu bixwazî bizanî? 🙂" }
    ]
  },

  /* ---------------- FRENCH ---------------- */
  "fr": {
    "greet": "Bonjour ! 👋 Je suis l'assistant du studio de Barakat. Demandez-moi <b>services</b>, <b>tarifs</b>, <b>délais</b>, ou comment <b>démarrer un projet</b>.",
    "fallback": "Je ne suis pas sûr — mais Barakat peut aider directement. Essayez la salle <b>Contact</b>, ou demandez-moi <i>tarifs, délais, révisions, paiement, fichiers, ou services</i>.",
    "quick": [{ "label": "Tarifs", "q": "prix" }, { "label": "Services", "q": "service" }, { "label": "Délais", "q": "délai" }, { "label": "Contact", "q": "contact" }],
    "kb": [
      { "k": ["service", "que faites", "proposez", "faites-vous"], "a": "Barakat propose <b>identité de marque & logos</b>, <b>édition & couvertures</b>, <b>affiches</b>, <b>réseaux sociaux</b>, <b>impression & factures</b>, et <b>vidéo & motion design</b>. Voir une catégorie ? Ouvrez les onglets de la salle Design." },
      { "k": ["prix", "tarif", "combien", "budget", "coût", "ça coûte"], "a": "Le prix dépend de l'ampleur. Points de départ :<br>• <b>Logo</b> — 100$ → 1 500$+<br>• <b>Identité complète</b> — 250$ → 2 500$<br>• <b>Affiche</b> — 15$ → 150$<br>• <b>Post réseaux</b> — 10$ → 25$<br>• <b>Vidéo (par min)</b> — dès 100$<br>• <b>Gestion mensuelle</b> — 250$ → 1 000$+<br>Pour un devis exact, envoyez un brief via la salle <b>Contact</b>." },
      { "k": ["logo", "marque", "identité", "branding"], "a": "<b>Logo & identité de marque :</b><br>• Création de logo — dès <b>100$</b> (simple) jusqu'à <b>1 500$+</b> (pro complet)<br>• Identité complète (logo, carte, dossier, affiche) — <b>250$ → 2 500$</b><br>Un logo est une marque, pas qu'une image — et les droits sont à vous. Voir l'onglet <b>Logo</b>." },
      { "k": ["affiche", "impression", "carte", "facture", "couverture", "poster"], "a": "<b>Impression & publicité :</b><br>• Affiche — <b>15$ → 150$</b><br>• Carte de visite — <b>10$ → 25$</b><br>• Facture / en-tête — <b>10$ → 20$</b> l'unité<br>• Couverture de livre — <b>50$ → 100$</b><br>• Mise en page intérieure — <b>1,5$ → 2,5$</b> la page" },
      { "k": ["post", "publication", "carrousel", "retouche"], "a": "<b>Réseaux sociaux & images :</b><br>• Un post — <b>10$ → 25$</b><br>• Carrousel (plusieurs images) — <b>25$ → 60$</b><br>• Retouche d'image — <b>10$ → 20$</b> par image" },
      { "k": ["vidéo", "motion", "reel", "montage", "animation"], "a": "<b>Vidéo & motion :</b><br>• Vidéo pub / cinématique — dès <b>100$ la minute</b> (avec tournage jusqu'à 1 500$)<br>• Motion graphics — <b>3$ → 10$ la seconde</b> (200$–600$ la minute)<br>• Reels / shorts (montage simple) — <b>15$ → 40$</b>" },
      { "k": ["gestion", "mensuel", "forfait", "ma page", "gérer"], "a": "<b>Gestion des réseaux sociaux</b> (mensuel) :<br>• Simple (8–10 posts + montage simple + réponses) — <b>250$ → 400$</b><br>• Moyen (15 posts + sponsoring + vidéo) — <b>500$ → 800$</b><br>• Pro (gestion complète + plan marketing) — <b>1 000$+</b>" },
      { "k": ["cher", "pourquoi", "moins cher", "juste une image", "coûteux"], "a": "Un logo n'est pas qu'une image — c'est le <b>visage</b> de votre activité. Vous ne payez pas le dessin, mais la recherche, l'expérience et la stratégie qui font ressortir votre marque parmi des centaines de concurrents. Le design bon marché signifie souvent perdre des clients." },
      { "k": ["délai", "temps", "combien de temps", "quand", "livraison", "prêt"], "a": "Délais typiques : <b>logo 3–7 jours ouvrés</b>, un post en <b>24–48 h</b>, une identité complète en <b>3–5 semaines</b>, une couverture en <b>~1 semaine</b>. Je donne une échéance fixe et la respecte. L'urgence est possible (petit supplément)." },
      { "k": ["révision", "pas aimé", "n'aime pas", "changer", "pas satisfait", "modifier"], "a": "Avant de commencer, on définit un <b>moodboard</b> (couleurs & style) pour cerner votre goût. Si ça ne convient toujours pas, j'inclus <b>2–3 révisions gratuites</b> jusqu'au résultat final." },
      { "k": ["paiement", "payer", "acompte", "avance", "verser"], "a": "Le paiement est partagé : <b>50% d'acompte</b> avant de commencer, et les <b>50%</b> restants après validation finale et avant l'envoi des fichiers sources." },
      { "k": ["remboursement", "annuler", "annulé", "rembourser"], "a": "L'acompte n'est pas remboursable, car il couvre le temps et l'effort déjà investis dans la recherche et le démarrage de votre projet." },
      { "k": ["remise", "réduction", "budget serré", "moins cher prix"], "a": "Les prix sont fixés selon le temps et l'effort. Si votre budget est serré, on peut réduire l'<b>ampleur</b> (ex. 3 posts au lieu de 5) — mais je ne réduis jamais la qualité." },
      { "k": ["fichier", "format", "png", "psd", "vectoriel"], "a": "Vous recevez tous les formats : <b>PNG</b> (transparent), <b>JPG</b> (réseaux), et les fichiers sources modifiables (<b>AI / PSD</b>) pour l'impression et le futur." },
      { "k": ["cmyk", "rgb", "couleur impression", "qualité impression", "différence couleur", "foncé"], "a": "Les fichiers d'impression sont préparés en <b>CMYK</b> à <b>300 dpi</b> pour des couleurs précises. L'écran utilise la lumière (RGB) et l'impression l'encre (CMYK) : une petite différence écran/impression est toujours naturelle." },
      { "k": ["fichier source", "source", "propriété", "fichier ouvert", "donnez-moi"], "a": "Les fichiers sources du logo & de l'identité (vectoriels) sont <b>à vous</b> — ils appartiennent à votre activité. Pour les posts et la vidéo, les fichiers ouverts (PSD/AEP) font partie de mon travail ; si vous les voulez pour de futures modifications, un montant fixe s'ajoute." },
      { "k": ["original", "copie", "modèle", "unique", "droits"], "a": "Chaque travail part de zéro avec idée + croquis. Je garantis que votre logo est <b>unique et que les droits sont à vous</b> — jamais une image Google ou un modèle. Si quelqu'un le copie, je fournis toutes les étapes de création pour le prouver." },
      { "k": ["urgent", "rapide", "vite", "aujourd'hui", "pressé"], "a": "Oui, l'urgence est possible — je peux faire de la place dans mon planning, mais un <b>supplément d'urgence (Rush Fee)</b> s'applique, car je dois suspendre d'autres clients et travailler des heures supplémentaires." },
      { "k": ["qui", "à propos", "expérience", "barakat", "ans"], "a": "Barakat Qurtas — designer graphique indépendant à <b>Erbil, Kurdistan</b> depuis <b>2014</b> (12+ ans), actuellement à la Direction des affaires médiatiques au Cabinet du Président. Plus de 1000 travaux, imprimé & numérique." },
      { "k": ["langue", "parle"], "a": "Barakat travaille en <b>kurde (sorani & kurmancî)</b>, <b>arabe</b>, <b>anglais</b>, et un peu de <b>français</b>." },
      { "k": ["contact", "email", "téléphone", "whatsapp", "embaucher", "démarrer"], "a": "Le plus simple pour joindre Barakat :<br>• ✉️ <a href='mailto:info@bqurtas.com'>info@bqurtas.com</a><br>• 📱 <a href='https://wa.me/9647517884985' target='_blank' rel='noopener'>WhatsApp +964 751 788 4985</a><br>Ou ouvrez la salle <b>Contact</b> et envoyez un brief." },
      { "k": ["livre", "couverture"], "a": "Les couvertures de livres sont une spécialité — 99+ couvertures. Ouvrez l'onglet <b>Livre</b>. Une couverture dès <b>50$</b>, mise en page intérieure dès <b>1,5$</b> la page." },
      { "k": ["bonjour", "salut", "coucou"], "a": "Bonjour ! 👋 Je suis l'assistant de studio de Barakat. Demandez-moi services, tarifs, délais, ou comment démarrer un projet." },
      { "k": ["merci"], "a": "Avec plaisir ! Autre chose que vous aimeriez savoir ? 🙂" }
    ]
  }

};
